# Configuration file for SmartTradeAI
api_keys:
  alpha_vantage: YOUR_ALPHA_VANTAGE_KEY
  news_api: YOUR_NEWS_API_KEY
  openai: YOUR_OPENAI_KEY
stocks:
  - AAPL
  - TSLA
  - NVDA
  - MSFT
  - AMZN
trade:
  risk_per_trade: 0.01
  broker: alpaca
